### ISSUE TITLE
Handling of fractional action space

### ISSUE THREAD

**Issue by masonlr** [moriartyjm/netzerotc#3]
The current action space supports `np.float` actions, i.e. stepping forward in fractions of a year: https://github.com/moriartyjm/netzerotc/blob/36317f9c38e002a35e01362ea834b41e239312bf/environment/reference_environment/env.py#L88-L93

The environment is currently however using integer indexing of data structures, for example when looking up the reward sensitivities: for example, when indexing into `param.IEV_RewardSensitivities` using `param.IEV_RewardSensitivities[scenario, sensitivityYear, 0]` the value of `sensitivityYear` is not necessarily an integer:
https://github.com/moriartyjm/netzerotc/blob/36317f9c38e002a35e01362ea834b41e239312bf/environment/reference_environment/env.py#L113

You can reproduce the resultant runtime error by creating a random agent:

```python
#!/usr/bin/env python

import gym

from util import Evaluate

env = gym.make("reference_environment:reference-environment-v0")

# evaluate = Evaluate(env, agent)
evaluate = Evaluate(env)

seeds = evaluate.read_seeds(fname="seeds.csv")
rewards = evaluate.random_agent(seeds)
```
which leads to:

```shell
Traceback (most recent call last):
  File "./evaluate.py", line 14, in <module>
    rewards = evaluate.random_agent(seeds)
  File "/Users/lrmason/github.com/moriatyjm/netzerotc/local_agent_training_and_evaluation/util.py", line 95, in random_agent
    self.env.step(action)
  File "/Users/lrmason/github.com/moriatyjm/netzerotc/environment/reference_environment/env.py", line 228, in step
    self.state, reward = apply_action(action, self.state)
  File "/Users/lrmason/github.com/moriatyjm/netzerotc/environment/reference_environment/env.py", line 128, in apply_action
    IEV_YearReward = param.IEV_Rewards[
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

**Comment by masonlr** [comment]
If we want a single action space then we _can't_ have the weights as fractions and the year-increaments as integers, i.e. something like 

```python
def action_space():
    act_low = np.zeros(
        2 * param.scenarios, dtype=int
    )  # scenario weights and scenario years to advance
    act_high = np.full(2 * param.scenarios, param.steps_per_episode, dtype=int)
    result = spaces.Box(act_low, act_high, dtype=int)
    return result
```

would break the scenario weights.

We probably should make a decision about whether we want to (i) support fractional stepping (using interpolation within the environment) or (ii) support integer weights (e.g. the agent needs to supply integer weights that sum to 100.

**Comment by moriartyjm** [comment]
Ah ok, nice catch - so we need to choose a global dtype for the action space.
Could a simple answer be to go with the `np.float32` dtype for the action space, and then modify it as needed in the `apply_action` ? So in this case, change https://github.com/moriartyjm/netzerotc/blob/36317f9c38e002a35e01362ea834b41e239312bf/environment/reference_environment/env.py#L101 
to `scenarioYears = (action[param.scenarios:]).astype(int)` ?

**Comment by masonlr** [comment]
Yep, we can round the years. I'm not 100% sure what the implications are for a typical training algorithm and continuity in the reward signal, e.g. if the training algorithm applies a small delta in the action space it won't see any gradient in the reward space (because of the rounding).

**Comment by moriartyjm** [comment]
Actually this seems good. Since the challenge to participants is to make training work, anything like this which prevents the default RL solvers working well out of the box should add interest to the challenge. So e.g. if successful participants implement fractional years in their training to get around this, that would be an interesting learning outcome. So our 'simplest nontrivial' philosophy looks good!

**Comment by moriartyjm** [comment]
Think we have resolved this, closing!
